[package]
authors = ["Johan Helsing <johanhelsing@gmail.com>"]
categories = ["game-development"]
description = "Rollback safe utilities and abstractions for Bevy"
edition = "2021"
keywords = ["gamedev", "bevy"]
license = "MIT OR Apache-2.0"
name = "bevy_roll_safe"
repository = "https://github.com/johanhelsing/bevy_roll_safe"
version = "0.1.0"

[features]
default = ["bevy_ggrs", "math_determinism"]
bevy_ggrs = ["dep:bevy_ggrs"]
math_determinism = ["bevy_math/libm"]

[dependencies]
bevy = { version = "0.13", default-features = false }
bevy_math = "0.13"
bevy_ggrs = { git = "https://github.com/bushrat011899/bevy_ggrs", branch = "Bevy0.13Update", optional = true, default-features = false }